### ISSUE TITLE
custom_menu data directory creates with wrong permissions

### ISSUE THREAD

**Issue by davetest** [lokothodida/gs-custom-menu#2]
Great plugin - love it!
But when installing current v0.5 custom_menu data directory is created with 341 permissions, so data doesn't save. Manually changing to 755 and it works like a dream. Also noted that custom_menu.php is listed as v0.4 in master branch files list, but as file has no embedded version ref, I don't know if this is latest version.
Thanks for another of your great plugins.

**Comment by lokothodida** [comment]
Issue should be resolved (I'll wait for confirmation). If it is, I'll tag the latest release as v0.6.

**Comment by davetest** [comment]
Issue seems resolved to me. Many thanks.

**Comment by lokothodida** [comment]
Thanks for the kind comments and for testing the plugin (and apologies for the late response time).
