### ISSUE TITLE
Fill URL from Slug

### ISSUE THREAD

**Issue by kalobyte** [lokothodida/gs-custom-menu#3]
There would be better, if the user can choose and fill automatically the URL field from the Slug field, because its already prepared and excepts any misstyping errors.

**Comment by lokothodida** [comment]
If the URL field is automatically filled in, then the user will need to manually change the URL prefixes if their domain or the URL structure changes. So as a compromise, the fix I've implemented on the current v0.6.1 beta is that it generates the canonical URL on the fly (when building the menu's HTML) if:

* there is a slug present
* the URL field is empty and
* a valid target has been selected (e.g. `_blank`)

Does that sound like a fair trade-off?

**Comment by lokothodida** [comment]
Fixed in [v0.6.1](https://github.com/lokothodida/gs-custom-menu/releases/tag/v0.6.1).
